#!/bin/bash

PATH="$HOME/.local/bin:$HOME/bin:/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin"

head()
{
    echo "Check file requirements.yml"
    echo
}


showhelp()
{
    head
    echo "Usage: $(basename $0) [OPTIONS]"
    echo 'OPTIONS:'
    echo '-h | --help:      Show this help screen'
    echo '-d | --diff-only: Show only different tags'
}

while [ "$1" ]; do
    case $1 in
        '-h' | '--help' | '?' )
            showhelp
            exit
            ;;
        '--diff-only' | '-d' )
            DIFF=1
            ;;
        * )
            ;;
    esac
    shift
done



RepoNameFile=$(mktemp)
WorkDir=$(pwd)

GREEN_SED='\\033[0;32m'
YELLOW_SED='\\033[1;33m'
RED_SED='\\033[0;31m'
NORM_SED='\\033[0m' # No Color
BOLD_SED='\\033[1m'

echo -e "__BOLD_NORM__RepoName__COL_NORM__\t__BOLD_NORM__LocalTag__COL_NORM__\t__BOLD_NORM__RemoteTag__COL_NORM__" > $RepoNameFile

GitRepos=$(find . -maxdepth 1 -mindepth 1 -name requirements.yml -print0 | xargs -0 grep "src" | awk '{print $3}' | sort | uniq)
for GitRepo in $GitRepos; do
  # LOCAL-TAG
  GitLocalTag=$(grep "$GitRepo" requirements.yml -A 4 | grep "version:" | awk '{print $2}')
 
  # REMOTE-TAG
  RepoTmpDir=$(mktemp -d --dry-run)
  git clone $GitRepo $RepoTmpDir -q
  cd ${RepoTmpDir}
  GitRepoTag=$(git tag --sort "v:refname"  --merged | tail -1)
  cd ${WorkDir}
  rm -rf ${RepoTmpDir}

  printf '%s\n%s' "$GitLocalTag" "$GitRepoTag" | sort -C -V
  if [[ $? -eq 0 ]];then
    if [[ $GitLocalTag != $GitRepoTag ]];then
      GitLocalTag=__COL_YELLOW__${GitLocalTag}__COL_NORM__
      GitRepoTag=__COL_GREEN__${GitRepoTag}__COL_NORM__
    else
      GitLocalTag=__COL_NORM__${GitLocalTag}__COL_NORM__
      GitRepoTag=__COL_NORM__${GitRepoTag}__COL_NORM__
    fi
  else
    GitLocalTag=__COL_RED__${GitLocalTag}__COL_NORM__
    GitRepoTag=__COL_YELLOW__${GitRepoTag}__COL_NORM__
  fi

  if [[ -z $DIFF ]]; then
    echo -e "__COL_NORM__${GitRepo}__COL_NORM__\t${GitLocalTag}\t${GitRepoTag}" >> ${RepoNameFile}
  else
    if [[ $GitLocalTag != $GitRepoTag ]];then
      echo -e "__COL_NORM__${GitRepo}__COL_NORM__\t${GitLocalTag}\t${GitRepoTag}" >> ${RepoNameFile}
    fi
  fi
done

DATA=$(column -t -s$'\t'  $RepoNameFile)
echo -e "$(sed -e "s/__COL_RED__/${RED_SED}/g" -e "s/__COL_GREEN__/${GREEN_SED}/g" -e "s/__COL_NORM__/${NORM_SED}/g" -e "s/__COL_YELLOW__/${YELLOW_SED}/g" -e "s/__BOLD_NORM__/${BOLD_SED}/g" <<< "$DATA")"
rm -f $RepoNameFile
